# Copyright (C) 2020 Johannes Endres
#
# SPDX-License-Identifier: MIT

image: node:lts

cache:
  key: node_modules
  paths:
    - node_modules/

lint:
  stage: test
  before_script:
    - git submodule update --init
    - npm install
  script:
    - npx web-ext lint
    - npx eslint src
    - "! grep -r --exclude-dir=photon-components-web TODO src"

sign:
  stage: deploy
  before_script:
    - npm install --loglevel error web-ext@7
    - git submodule update --init
  script:
    # web-ext sign always fails (as documented), so manipulate the return code
    - "npx web-ext sign -s src --channel=listed --api-url-prefix=https://addons.thunderbird.net/api/v3 || true"
  environment:
    name: Add-ons for Thunderbird
    url: https://addons.thunderbird.net/de/thunderbird/addon/filelink-nextcloud-owncloud/
  rules:
    # Only sign tagged releases
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

release_job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: sign
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  before_script:
    - git submodule update --init
  script:
    - echo "Creating Release"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'Installation via Thunderbird Add-ons'
          url: "https://addons.thunderbird.net/de/thunderbird/addon/filelink-nextcloud-owncloud/versions/$CI_COMMIT_TAG"

deploy-pages:
  stage: deploy
  script:
    - node build-tools/build-pages.mjs
  pages: true
  artifacts:
    paths:
      - public
  environment:
    name: "Pages"
    url: "${CI_PAGES_URL}"
  rules:
  - if: $CI_COMMIT_REF_PROTECTED == "true"
