# Copyright (C) 2025 Johannes Endres
#
# SPDX-License-Identifier: MIT

variables:
  # Get submodules automatically
  GIT_SUBMODULE_STRATEGY: normal
  # Use more efficient fs driver
  DOCKER_DRIVER: overlay2

default:
  artifacts:
    untracked: false
    access: developer
    expire_in: "10 days"

# Template for jobs that use node
.node_job:
  image: node:lts-alpine
  before_script:
    - apk add grep
    - npm install --loglevel=error
  # Cache installed node modules as this might be faster than reinstalling them
  cache:
    key: node_modules
    paths:
      - node_modules/

## Jobs
Static Tests:
  extends: .node_job
  stage: test
  interruptible: true
  rules:
    - if: $CI_COMMIT_TITLE =~ /^(docs|ci|build):/
      when: never
    # Categorized commit of source
    - if: $CI_COMMIT_TITLE =~ /^(fix|eat|perf|test|refactor|style):/
  script:
    - npx web-ext lint
    - npx eslint src
    - "! grep -Er --exclude-dir=photon-components-web '(TODO|debug)' src"

REUSE compliance:
  stage: test
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  interruptible: true
  rules:
    # Categorized commit
    - if: $CI_COMMIT_TITLE =~ /^(docs|ci|build|fix|feat|perf|test|refactor|style):/
  script:
    - reuse lint

Check build tools:
  extends: .node_job
  stage: test
  interruptible: true
  rules:
    - if: $CI_COMMIT_TITLE =~ /^build:/
  script:
    - npx eslint build-tools

Deploy to Thunderbird Add-ons:
  extends: .node_job
  stage: deploy
  script:
    # Check if the version in manifest.json and $CI_COMMIT_TAG match
    - grep -E \"version\":\\s+\"$CI_COMMIT_TAG\" src/manifest.json
    # web-ext sign always fails (as documented), so manipulate the return code
    - "npx web-ext sign || true"
  rules:
    # Only sign tagged releases
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

Create a release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cli:latest
  needs:
    - job: Deploy to Thunderbird Add-ons
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  script:
    # Check if the version in manifest.json and $CI_COMMIT_TAG match
    - grep -E \"version\":\\s+\"$CI_COMMIT_TAG\" src/manifest.json
  release:
    description: "$(cat build-tools/release-notes-template.md)\n$CI_COMMIT_MESSAGE"
    tag_name: "$CI_COMMIT_TAG"

Build pages:
  extends: .node_job
  stage: deploy
  script:
    # This script only works if GITLAB_PROJECT_TOKEN is a valid token
    - node build-tools/build-pages.mjs
  pages: true
  artifacts:
    expire_in: 1 hour
  rules:
    # Explicit update of documentation
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE =~ /^docs:/
    # Release that might affect documentation
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
