# Copyright (C) 2025 Johannes Endres
#
# SPDX-License-Identifier: MIT

variables:
  # Get submodules automatically
  GIT_SUBMODULE_STRATEGY: normal
  # Use more efficient fs driver
  DOCKER_DRIVER: overlay2

default:
  artifacts:
    untracked: false
    access: developer
    expire_in: "10 days"

# Template for jobs that use node
.node_job:
  image: node:lts-alpine
  before_script:
    - npm install --loglevel=error --allow-git=root
  # Cache installed node modules as this might be faster than reinstalling them
  cache:
    key: node_modules
    paths:
      - node_modules/

## Tests
Static Tests:
  extends: .node_job
  stage: test
  interruptible: true
  rules:
    - if: $CI_COMMIT_TITLE =~ /^(docs|ci|build):/
      when: never
    # Categorized commit of source
    - if: $CI_COMMIT_TITLE =~ /^(fix|feat|perf|test|refactor|style):/
    # Also on tagged releases
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  script:
    - npx web-ext lint
    - npx eslint src

REUSE compliance:
  stage: test
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  interruptible: true
  rules:
    # Categorized commit
    - if: $CI_COMMIT_TITLE =~ /^(docs|ci|build|fix|feat|perf|test|refactor|style):/
    # Also on tagged releases
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  script:
    - reuse lint

Check build tools:
  extends: .node_job
  stage: test
  interruptible: true
  rules:
    - if: $CI_COMMIT_TITLE =~ /^build:/
  script:
    - npx eslint build-tools

Additional pre-release tests:
  stage: test
  image: alpine:latest
  rules:
    # Only check tagged releases
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  script:
    # Check if the version in manifest.json and $CI_COMMIT_TAG match
    - grep -E \"version\":\\s+\"$CI_COMMIT_TAG\" src/manifest.json

# Deployments
Deploy to Thunderbird Add-ons:
  extends: .node_job
  stage: deploy
  script:
    # web-ext sign always fails (as documented), so manipulate the return code
    - "npx web-ext@7 sign --channel=listed --api-url-prefix=https://addons.thunderbird.net/api/v4 || true"
  rules:
    # Only sign tagged version on master branch
    - if: $CI_COMMIT_BRANCH == "master" && '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

Create a release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cli:latest
  needs:
    - job: Deploy to Thunderbird Add-ons
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  script:
    - echo "Creating release $CI_COMMIT_TAG"
  release:
    description: |
      # Installation

      [![Get the Addon](https://raw.githubusercontent.com/thunderbird/webext-support/refs/heads/master/images/get-the-addon.svg)](https://addons.thunderbird.net/thunderbird/addon/filelink-nextcloud-owncloud/)

      ## Changes

      $CI_COMMIT_MESSAGE
    tag_name: "$CI_COMMIT_TAG"

Build pages:
  extends: .node_job
  stage: deploy
  script:
    - cp README.md docs/docs/index.md
    - cd docs
    - npx okidoki generate
  pages: true
  artifacts:
    expire_in: 1 hour
  rules:
    # Explicit update of documentation
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE =~ /^docs:/
    # Release that might affect documentation
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

# Gitlab default static analysis
sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
