# Copyright (C) 2025 Johannes Endres
#
# SPDX-License-Identifier: MIT

## Global configuration
cache:
  key: node_modules
  paths:
    - node_modules/

default:
  image: node:lts
  before_script:
    - "which npm && npm install --loglevel error"

# Get submodules
variables:
  GIT_SUBMODULE_STRATEGY: normal

## Jobs
Static Tests:
  stage: test
  script:
    - npx web-ext lint
    - npx eslint src
    - "! grep -r --exclude-dir=photon-components-web TODO src"
 
REUSE compliance:
  stage: test
  image: python:3
  script:
    - pip3 install reuse
    - reuse lint

Deploy to Thunderbird Add-ons:
  stage: deploy
  script:
    # web-ext sign always fails (as documented), so manipulate the return code
    - "npx web-ext sign || true"
  environment:
    name: Add-ons for Thunderbird
    url: https://addons.thunderbird.net/de/thunderbird/addon/filelink-nextcloud-owncloud/
  rules:
    # Only sign tagged releases
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

Create a release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: Deploy to Thunderbird Add-ons
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  script:
    - "true"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Installation via Thunderbird Add-ons'
          url: "https://addons.thunderbird.net/de/thunderbird/addon/filelink-nextcloud-owncloud/versions/$CI_COMMIT_TAG"

Build pages:
  stage: deploy
  script:
  # This script only works if GITLAB_PROJECT_TOKEN is a valid token
    - node build-tools/build-pages.mjs
  pages: true
  artifacts:
    paths:
      - public
  environment:
    name: "Pages"
    url: "${CI_PAGES_URL}"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
