# Copyright (C) 2025 Johannes Endres
#
# SPDX-License-Identifier: MIT

variables:
  # Get submodules automatically
  GIT_SUBMODULE_STRATEGY: normal
  # Use more efficient fs driver
  DOCKER_DRIVER: overlay2

default:
  artifacts:
    untracked: false
    access: developer
    expire_in: "30 days"

# Template for jobs that use node
.node_job:
  image: node:lts
  before_script:
    - npm install --loglevel=error
  # Cache installed node modules as this might be faster than reinstalling them
  cache:
    key: node_modules
    paths:
      - node_modules/

## Jobs
Static Tests:
  extends: .node_job
  stage: test
  interruptible: true
  rules:
    - if: $CI_COMMIT_TITLE =~ /^(docs|ci|build):/
      when: never
    # Categorized commit
    - if: $CI_COMMIT_TITLE =~ /^(f(ix|eat)!?|perf|test|refactor|style):/
  script:
    - npx web-ext lint
    - npx eslint src
    - "! grep -r --exclude-dir=photon-components-web TODO src"

REUSE compliance:
  stage: test
  image: python:3
  interruptible: true
  script:
    - pip3 install reuse
    - reuse lint

Check build tools:
  extends: .node_job
  stage: test
  interruptible: true
  rules:
    - if: $CI_COMMIT_TITLE =~ /^build:/
  script:
    - npx eslint build-tools

Bump version:
  # Autmatically increment the version and add a tag, triggering the release
  extends: .node_job
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE =~ /^(feat|fix)!?:/
  script:
    - LAST_VERSION=`git tag -l | egrep '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -n | tail -1`
    - NEW_VERSION=`node build-tools/bump-semver.js ${CI_COMMIT_TITLE%:*} $LAST_VERSION`
    - git tag $NEW_VERSION
    # GITLAB_PROJECT_TOKEN must have role "Developer" and scope "write_repository"
    - git remote add master ${CI_REPOSITORY_URL/gitlab-ci-token*@/release_bot:$GITLAB_PROJECT_TOKEN@}
    - git push --tags master

Deploy to Thunderbird Add-ons:
  extends: .node_job
  stage: deploy
  script:
    # web-ext sign always fails (as documented), so manipulate the return code
    - "npx web-ext sign || true"
  environment:
    name: Add-ons for Thunderbird
    url: https://addons.thunderbird.net/de/thunderbird/addon/filelink-nextcloud-owncloud/
  rules:
    # Only sign tagged releases
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

Create a release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: Deploy to Thunderbird Add-ons
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  script:
    - "true"
  release:
    name: "Release $CI_COMMIT_TAG"
    description: "Release $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    assets:
      links:
        - name: "Installation via Thunderbird Add-ons"
          url: "https://addons.thunderbird.net/de/thunderbird/addon/filelink-nextcloud-owncloud/versions/$CI_COMMIT_TAG"

Build pages:
  extends: .node_job
  stage: deploy
  script:
    # This script only works if GITLAB_PROJECT_TOKEN is a valid token
    - node build-tools/build-pages.mjs
  pages: true
  artifacts:
    expire_in: 1 hour
  environment:
    name: "Pages"
    url: "$CI_PAGES_URL"
  rules:
    # Explicit update of documentation
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE =~ /^docs:/
    # Release that might affect documentation
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
